### ISSUE TITLE
feature request: clear selected files/folders

### ISSUE THREAD

**Issue by og900aero** [KKV9/compress.yazi#6]
Could you implement clear selected files and folders after compressed that?

**Comment by KKV9** [comment]
Hi, I don't plan on implementing this because a keybind can be used instead. Feel free to submit a PR if this feature is important to you. A `--clear` option or similar is required as some people may want to keep files selected.
See the following documentation [https://yazi-rs.github.io/docs/configuration/keymap#manager.select_all](url).

**Comment by og900aero** [comment]
> @og900aero answered you in [sxyazi/yazi#1447](https://github.com/sxyazi/yazi/discussions/1447) just in case
> 
> ```toml
> [[manager.prepend_keymap]]
> on = ["<your_keymap>"]
> run = ["plugin compress", "select_all --state=false"]
> desc = "Archive selected files"
> ```

It is not working, because run select_all --state=false command before I type archive name. It is not problem, if I selected only one folders, but if I selected more folders, then compress only last selected folders.
